baseURL: http://example.org/
languageCode: en
title: My New "Hugo Site"
theme: simple
paginate: 1
googleAnalytics: UA-123456
enableRobotsTXT: true

taxonomies:
  series: series
  tag: tags

outputs:
  home:
    - HTML
    - RSS
    - JSON

markup:
  highlight:
    tabWidth: 2
    noClasses: false

privacy:
  googleAnalytics:
    anonymizeIP: true
    respectDoNotTrack: true
    useSessionStorage: true

  twitter:
    enableDNT: true

  youtube:
    privacyEnhanced: true

menu:
  footer:
    - name: about me
      pre: ">"
      post: "<"
      url: /about/
    - name: projects
      url: /projects/
    - name: blog
      url: /posts/

params:
  titleDelim: "|"

  publisher:
    logo: /apple-touch-icon.png
    twitter: mynewhugosite
    facebook: mynewhugosite

  author:
    name: Peter
    twitter: peter
    facebook: peter

  pagination:
    spanStart: 0
    spanMiddleLeft: 2
    spanMiddleRight: 2
    spanEnd: 0

  taxonomies:
    tags:
      js:
        title: JavaScript
      html:
        title: HTML

  css:
    - /static/modal.min.css
    - /popup.min.css
    - bundle.min.css
    - https://fonts.googleapis.com/css2?family=Fira+Code:wght@400;700&display=swap

  js:
    - /ui.min.js
    - /static/logic.min.js
    - bundle.min.js

  favicon:
    maskIcon: "#aaaaaa"
    themeColor: "#000000"
    msapplicationTileColor: "#bbbbbb"

  share:
    - twitter

  theme: true

  search: true
