baseURL: http://example.org/
languageCode: en
title: My New "Hugo Site"
theme: simple
paginate: 1
googleAnalytics: UA-123456
enableRobotsTXT: true

taxonomies:
  series: series
  tag: tags

outputs:
  home:
    - HTML
    - RSS
    - JSON

privacy:
  googleAnalytics:
    anonymizeIP: true

  twitter:
    enableDNT: true

  youtube:
    privacyEnhanced: true

params:
  publisher:
    logo: /apple-touch-icon.png
    twitter: mynewhugosite
    facebook: mynewhugosite

  author:
    name: Peter
    twitter: peter
    facebook: peter

  pagination:
    spanStart: 0
    spanMiddleLeft: 2
    spanMiddleRight: 2
    spanEnd: 0

  taxonomies:
    tags:
      js:
        title: JavaScript
      html:
        title: HTML

  css:
    - /static/modal.min.css
    - /popup.min.css

  js:
    - /ui.min.js
    - /static/logic.min.js
    - bundle.min.js

  favicon:
    maskIcon: "#aaaaaa"
    themeColor: "#000000"
    msapplicationTileColor: "#bbbbbb"
