baseURL: http://example.org/
languageCode: en
title: My New "Hugo Site"
theme: simple
googleAnalytics: UA-123456
enableRobotsTXT: true

taxonomies:
  series: series
  tag: tags

outputs:
  home:
    - HTML
    - RSS
    - JSON

markup:
  highlight:
    tabWidth: 2
    noClasses: false

privacy:
  googleAnalytics:
    anonymizeIP: true
    respectDoNotTrack: true
    useSessionStorage: true

  twitter:
    enableDNT: true

  youtube:
    privacyEnhanced: true

menu:
  footer:
    - name: about me
      pre: "&rarr;"
      post: "&larr;"
      url: /about/
    - name: projects
      url: /projects/
    - name: blog
      url: /posts/

params:
  publisher:
    logo: /apple-touch-icon.png
    twitter: mynewhugosite
    facebook: mynewhugosite

  author:
    name: &authorName Peter
    twitter: peter
    facebook: peter
    github: peter
    youtube: peter
    instagram: peter
    linkedin: peter
    reddit: peter
    email: &authorEmail hey@gmail.com
    rss: /index.xml
  authorSocialOrder:
    - email
    - github
    - facebook
    - twitter
    - youtube
    - instagram
    - linkedin
    - reddit
    - rss

  css:
    - /static/modal.min.css
    - /popup.min.css
    - bundle.min.css
    - https://fonts.googleapis.com/css2?family=Fira+Code:wght@400;700&display=swap

  js:
    - /ui.min.js
    - /static/logic.min.js
    - bundle.min.js

  favicon:
    maskIcon: "#aaaaaa"
    themeColor: "#000000"
    msapplicationTileColor: "#bbbbbb"

  titleDelim: "|"

  paginate: 1
  pagination:
    spanStart: 0
    spanMiddleLeft: 2
    spanMiddleRight: 2
    spanEnd: 0

  share:
    - twitter

  theme:
    enable: true
    class: dark
    nextThemeText: Light

  search:
    enable: true
    placeholder: Search Articles...

author:
  name: *authorName
  email: *authorEmail
