baseURL: http://example.org/
languageCode: en
title: My New "Hugo Site"
theme: simple
googleAnalytics: UA-150679205-1
enableRobotsTXT: true

taxonomies:
  tag: tags

outputs:
  home:
    - HTML
    - RSS
    - JSON

markup:
  highlight:
    tabWidth: 2
    noClasses: false

privacy:
  googleAnalytics:
    anonymizeIP: true
    respectDoNotTrack: true
    useSessionStorage: true

  twitter:
    enableDNT: true

  youtube:
    privacyEnhanced: true

menu:
  footer:
    - name: about me
      pre: "&rarr;"
      post: "&larr;"
      url: /about/
    - name: projects
      url: /projects/
    - name: blog
      url: /posts/
    - name: RSS
      url: /index.xml

params:
  sinceYear: 2020

  publisher:
    logo: /apple-touch-icon.png
    twitter: mynewhugosite
    facebook: mynewhugosite

  author:
    name: &authorName Peter
    twitter: peter
    facebook: peter
    github: peter
    youtube: peter
    instagram: peter
    linkedin: peter
    reddit: peter
    codepen: peter
    email: &authorEmail hey@gmail.com
  authorSocialOrder:
    - email
    - github
    - codepen
    - facebook
    - twitter
    - youtube
    - instagram
    - linkedin
    - reddit

  css:
    - /static/modal.min.css
    - /popup.min.css
    - bundle.min.css
    - https://fonts.googleapis.com/css2?family=Fira+Mono:wght@400;700&display=swap

  js:
    - /ui.min.js
    - /static/logic.min.js
    - bundle.min.js

  favicon:
    maskIcon: "#aaaaaa"
    themeColor: "#000000"
    msapplicationTileColor: "#bbbbbb"

  titleDelim: "|"

  paginate: 1
  pagination:
    spanStart: 0
    spanMiddleLeft: 2
    spanMiddleRight: 2
    spanEnd: 0

  share:
    - twitter

  theme:
    enable: true
    class: dark
    nextThemeText: Light

  search:
    enable: true
    placeholder: Search Articles...

  subscriptionForm:
    emailoctopus:
      url: https://emailoctopus.com/lists/ad61168e-9be4-11ea-a3d0-06b4694bee2a/members/embedded/1.3/add
      emailFieldName: field_0
      class:
      title: Just Subscribe
      description:
      submitText: Subscribe
      placeholder: Enter your email
      footer:

    sender:
      url: https://app.sender.net/forms/sender_subscription/12239/3f090bd3
      emailFieldName: email
      class:
      title: Get new articles to your inbox
      description: Approximately 1 email a week.
      submitText: Subscribe
      placeholder: Your email
      footer: <a href="http://sender.net" rel="nofollow noopener noreferrer" target="_blank">Powered by Sender.net</a>

    tinyletter:
      url: https://tinyletter.com/bodi_vomoto_com
      emailFieldName: email
      class:
      title: Get new articles to your inbox
      description: Approximately 1 email a week.
      submitText: Subscribe
      placeholder: Your email
      footer: <a href="https://tinyletter.com" rel="nofollow noopener noreferrer" target="_blank">Powered by TinyLetter</a>

author:
  name: *authorName
  email: *authorEmail
